export const ActionTypes = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    SORT_HIGH_TO_LOW: 'SORT_HIGH_TO_LOW',
    SORT_LOW_TO_HIGH: 'SORT_LOW_TO_HIGH',
    FILTER_PRICE: 'FILTER_PRICE',
    FILTER_AVAILABILITY: 'FILTER_AVAILABILITY'
}